spring:
  application:
    name: spring-data-redis-cashe
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SECURE_PAYMENT
    password: SECURE_PAYMENT

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false #Database ile isi bitende session kill olur
    properties:
      hibernate:
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 8
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false

server:
  port: 8808

logging:
  level:
    root: INFO
    com.springdatarediscache.logging: INFO
    com.springdatarediscache.service: ERROR


